export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST"
export const USER_SIGNIN_SUCCES = "USER_SIGNIN_SUCCES"
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL"
export const USER_SIGNOUT = "USER_SIGNOUT"

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCES = "USER_REGISTER_SUCCES"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"

